import 'package:get/get.dart';

class AppStrings extends Translations {
  // General
  static const String appName = 'appName',
      selectLanguage = 'selectLanguage',
      viewRequest = 'View Request',
      getStarted = 'Get Started',
      cancel = 'cancel',
      done = 'done',
      skip = 'skip',
      next = 'next',
      edit = 'edit',
      remove = 'remove',
      delete = 'delete',
      change = 'change',
      save = 'save',
      continueText = 'continueText',
      or = 'or',
      update = 'update',
      search = 'search',
      cad = 'cad',
      letsGo = 'letsGo';

  // Onboarding (Matches your Controller)
  static const String findTrustedHelp = 'findTrustedHelp',
      chatTrackGet = 'chatTrackGet',
      postTasks = 'postTasks',
      onBoardingSubTitle1 =
          'onBoardingSubTitle1', // Added
      onBoardingSubTitle2 =
          'onBoardingSubTitle2', // Added
      onBoardingSubTitle3 =
          'onBoardingSubTitle3', // Added
      createAccount = 'createAccount',
      signIn = 'signIn';

  // Role Selection
  static const String tellUsAboutYourself = 'tellUsAboutYourself',
      iNeedHelp = 'iNeedHelp',
      iNeedHelpDesc = 'iNeedHelpDesc',
      iWantToWork = 'iWantToWork',
      iWantToWorkDesc = 'iWantToWorkDesc';

  // Auth
  static const String firstName = 'firstName',
      lastName = 'lastName',
      email = 'email',
      password = 'password',
      phoneNumber = 'phoneNumber',
      city = 'city',
      alreadyHaveAccount = 'Already have an account?',
      orCreateAccount = 'orCreateAccount',
      signUp = 'signUp',
      continueWithGoogle = 'continueWithGoogle',
      continueWithApple = 'continueWithApple',
      termsOfService = 'termsOfService',
      privacyPolicy = 'privacyPolicy',
      bySigningUp = 'bySigningUp',
      and = 'and',
      enterVerificationCode = 'enterVerificationCode',
      codeSentTo = 'codeSentTo',
      resendCode = 'resendCode',
      haventGotCode = 'haventGotCode';

  // Navigation & Home
  static const String home = 'home',
      order = 'order',
      message = 'message',
      profile = 'profile',
      letLocal = 'letLocal',
      expertsHelp = 'expertsHelp',
      you = 'you',
      letLocalExperts = 'letLocalExperts',
      create = 'create',
      serviceCategory = 'serviceCategory',
      locationName = 'locationName',
      addressDetail = 'addressDetail',
      notification = 'notification';

  // Task Creation
  static const String createTask = 'createTask',
      category = 'category',
      chooseCategory = 'chooseCategory',
      taskTitle = 'taskTitle',
      taskTitleHint = 'taskTitleHint',
      addressArea = 'addressArea',
      addressHint = 'addressHint',
      selectDate = 'selectDate',
      selectTime = 'selectTime',
      details = 'details',
      detailsHint = 'detailsHint',
      budget = 'budget',
      budgetHint = 'budgetHint',
      postTask = 'postTask',
      goOrder = 'goOrder',
      taskPosted = 'taskPosted',
      taskerRequestOffer = 'taskerRequestOffer',
      chatAndGetItDone = 'chatAndGetItDone',
      goToMyTask = 'goToMyTask';

  // Categories
  static const String furnitureAssembly = 'furnitureAssembly',
      homeAssistance = 'homeAssistance',
      minorRepairs = 'minorRepairs',
      petServices = 'petServices',
      companionService = 'companionService',
      marketingPromotion = 'marketingPromotion',
      lockSmith = 'lockSmith',
      gardenCleaning = 'gardenCleaning';

  // Orders & Reviews
  static const String allOrder = 'allOrder',
      confirm = 'confirm',
      completed = 'completed',
      viewOrder = 'viewOrder',
      progress = 'progress',
      created = 'created',
      request = 'Offer Help',
      requestTitle = 'requestTitle',
      accept = 'accept',
      decline = 'decline',
      chooseServiceCategory = 'chooseServiceCategory',
      review = 'review',
      cantUndo = 'cantUndo',
      taskCompleted = 'taskCompleted',
      tasks = 'tasks',
      reviews = 'reviews',
      skills = 'skills',
      seeMore = 'seeMore',
      noOrders = 'noOrders',
      giveFeedback = 'giveFeedback',
      giveAFeedback = 'Give a Feedback',
      deleted = 'deleted',
      orderDeleted = 'orderDeleted',
      rateExperience = 'rateExperience',
      feedbackDesc = 'feedbackDesc',
      rateMark = 'rateMark',
      shareExperienceHint = 'shareExperienceHint',
      submitReview = 'submitReview',
      reviewSubmitted = 'reviewSubmitted',
      pleaseSelectRating = 'pleaseSelectRating',
      rateExpTitle = 'rateExpTitle',
      postedBy = 'postedBy',
      distance = 'distance',
      offerHelp = 'offerHelp',
      orderOtp = 'orderOtp',
      nicolas = 'nicolas',
      alexSmith = 'alexSmith',
      thankYouFeedback = 'thankYouFeedback',
      reviewSubmittedSuccess = 'reviewSubmittedSuccess',
      backToHome = 'backToHome';

  // Chat & Messages
  static const String messages = 'messages', typeMessage = 'typeMessage';

  // Billing & Payments
  static const String billingAndPayments = 'billingAndPayments',
      manageBillingMethod = 'manageBillingMethod',
      manageBillingDesc = 'manageBillingDesc',
      addBillingMethod = 'addBillingMethod',
      cardNumber = 'cardNumber',
      cardHolderName = 'cardHolderName',
      mm = 'mm',
      yy = 'yy',
      cvc = 'cvc',
      address = 'address',
      postalCode = 'postalCode',
      paymentSuccessful = 'paymentSuccessful',
      amount = 'amount',
      paymentMethod = 'paymentMethod',
      enterAmount = 'enterAmount',
      paymentIsReleased = 'paymentIsReleased',
      pay = 'pay';

  // Account & Settings
  static const String account = 'account',
      changePassword = 'changePassword',
      payment = 'payment',
      about = 'about',
      signOut = 'signOut',
      supportTicket = 'supportTicket',
      currentPassword = 'currentPassword',
      newPassword = 'newPassword',
      confirmPassword = 'confirmPassword',
      forgotPassword = 'forgotPassword',
      subject = 'subject',
      orderLabel = 'orderLabel',
      attachment = 'attachment',
      yourMessage = 'yourMessage',
      nameExample = 'nameExample',
      selectYourOrder = 'selectYourOrder',
      addAttachment = 'addAttachment',
      termsConfirmText1 = 'termsConfirmText1',
      termsConfirmText2 = 'termsConfirmText2',
      privacyStatement = 'privacyStatement',
      photo = 'photo',
      name = 'name',
      changeName = 'changeName',
      changeEmail = 'changeEmail',
      changePhoneNumber = 'changePhoneNumber',
      changeCity = 'changeCity',
      changePhoto = 'changePhoto',
      language = 'language',
      english = 'english',
      chinese = 'chinese',
      sanFranciscoCA = 'sanFranciscoCA',
      taskCompletedCount = 'taskCompletedCount',
      camera = 'camera',
      photoGallery = 'photoGallery',
      document = 'document',
      submitTicket = 'submitTicket',
      attention = 'attention',
      acceptTermsWarning = 'acceptTermsWarning',
      success = 'success',
      ticketSubmitted = 'ticketSubmitted',
      ticketHistory = 'ticketHistory',
      resolved = 'resolved';

  // Notifications & Time
  static const String notificationRequest = 'notificationRequest',
      notificationMessage = 'notificationMessage',
      notificationSystem = 'notificationSystem',
      notificationCompleted = 'notificationCompleted',
      notificationRate = 'notificationRate',
      timeHoursAgo = 'timeHoursAgo',
      timeMinutesAgo = 'timeMinutesAgo',
      strikeLateCancellation = 'strikeLateCancellation',
      visibilityAffected = 'visibilityAffected',
      reposts = 'reposts',
      overview = 'overview',
      transactionHistory = 'transactionHistory',
      refId = 'refId',
      serviceFee = 'serviceFee',
      deposit = 'deposit',
      takePhoto = 'takePhoto',
      chooseFromLibrary = 'chooseFromLibrary',
      justNow = 'justNow',
      phoneHint = 'phoneHint',
      shortBio = 'shortBio',
      tellYourWorkExp = 'tellYourWorkExp',
      proposedBudget = 'proposedBudget',
      submitRequest = 'submitRequest',
      reset = 'reset',
      apply = 'apply',
      myJob = 'myJob',
      allJob = 'allJob',
      accepted = 'accepted',
      pending = 'pending',
      viewTask = 'viewTask',
      confirmed = 'confirmed',
      startWork = 'startWork',
      finishWork = 'finishWork',
      completeTheTask = 'completeTheTask',
      otpInstruction = 'otpInstruction',
      completeWork = 'completeWork',
      report = 'report',
      workInProgress = 'workInProgress',
      inReview = 'inReview',
      available = 'available',
      paymentBanner = 'paymentBanner',
      chatBanner = 'chatBanner',
      orderBanner = 'orderBanner',
      successBanner = 'successBanner',
      privacyBanner = 'privacyBanner';

  // Verification
  static const String accountVerification = 'accountVerification',
      documentVerification = 'documentVerification',
      documentType = 'documentType',
      idCard = 'idCard',
      passport = 'passport',
      fullName = 'fullName',
      dateOfBirth = 'dateOfBirth',
      idNumber = 'idNumber',
      takePicturesOfId = 'takePicturesOfId',
      provideIdInfo = 'provideIdInfo',
      verified = 'verified',
      notVerified = 'notVerified',
      placeIdInFrame = 'placeIdInFrame',
      verificationSuccessful = 'verificationSuccessful',
      verificationFailed = 'verificationFailed',
      close = 'close',
      tryAgain = 'tryAgain',
      confirmLocation = 'confirmLocation',
      myLocation = 'myLocation',
      beFirstToHelp = 'beFirstToHelp',
      noRequestsRightNow = 'noRequestsRightNow',
      securePayment = 'securePayment',
      paymentReleasedCompletion = 'paymentReleasedCompletion',
      beSpecificDetails = 'beSpecificDetails',
      tenKVerified = 'tenKVerified',
      oneHundredPercent = 'oneHundredPercent',
      ninetyNinePercent = 'ninetyNinePercent',
      helpers = 'helpers',
      securePayBadge = 'securePayBadge',
      successRate = 'successRate',
      communitySafetyOtp = 'communitySafetyOtp',
      signOutConfirm = 'signOutConfirm';

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      appName: 'Help',
      getStarted: 'Get Started',
      selectLanguage: 'Select Language',
      cancel: 'Cancel',
      done: 'Done',
      skip: 'Skip',
      next: 'Next',
      edit: 'Edit',
      remove: 'Remove',
      delete: 'Delete',
      change: 'Change',
      save: 'Save',
      continueText: 'Continue',
      or: 'or',
      update: 'Update',
      search: 'Search',
      cad: 'CAD',
      letsGo: 'Let\'s Go',
      findTrustedHelp: 'Find Trusted Help Nearby',
      chatTrackGet: 'Chat, Track & Get Things Done',
      postTasks: 'Post Tasks in Minutes',
      onBoardingSubTitle1: 'Post a task and connect with reliable people.',
      onBoardingSubTitle2: 'Manage your tasks and track progress easily.',
      onBoardingSubTitle3: 'Secure communication and payments guaranteed.',
      createAccount: 'Create account',
      signIn: 'Sign in',
      tellUsAboutYourself: 'Tell us about yourself',
      iNeedHelp: 'I need help',
      iNeedHelpDesc: 'Getting things done with help from professionals',
      iWantToWork: 'I want to work',
      iWantToWorkDesc: 'Helping the community while earning securely',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      password: 'Password',
      phoneNumber: 'Phone Number',
      city: 'City',
      alreadyHaveAccount: 'Already have an account?',
      orCreateAccount: 'Or, Create account',
      signUp: 'Sign up',
      continueWithGoogle: 'Continue with Google',
      continueWithApple: 'Continue with Apple',
      termsOfService: 'Terms of Service',
      privacyPolicy: 'Privacy Policy',
      bySigningUp: 'By signing up, you agree to our ',
      and: ' and ',
      enterVerificationCode: 'Enter verification code',
      codeSentTo: 'Code will be sent to',
      resendCode: 'Resend Code',
      haventGotCode: "Haven't got the code yet?",
      home: 'Home',
      order: 'Order',
      message: 'Message',
      profile: 'Profile',
      letLocal: 'Let Local',
      expertsHelp: 'Experts Help',
      you: 'You',
      letLocalExperts: 'Let Local Experts Help You',
      create: 'Create task',
      serviceCategory: 'Service Category',
      locationName: 'San Francisco',
      addressDetail: '75 Wellington Street, ON K1A 0A2',
      notification: 'Notification',
      createTask: 'Create task',
      category: 'Category',
      chooseCategory: 'Choose category',
      taskTitle: 'Task title',
      taskTitleHint: 'e.g. Assemble an IKEA Desk',
      addressArea: 'Address / Area',
      addressHint: 'e.g. San Francisco CA',
      selectDate: 'Select date',
      selectTime: 'Select time',
      details: 'Details',
      detailsHint: 'Describe the work',
      budget: 'Budget',
      budgetHint: '\$80-\$100',
      postTask: 'Post task',
      goOrder: 'Go to my order',
      taskPosted: 'Your task is posted. Here’s what’s next',
      taskerRequestOffer: 'Tasker request offer',
      chatAndGetItDone: 'Chat and get it done!',
      goToMyTask: 'Go to my task',
      furnitureAssembly: 'Furniture assembly',
      homeAssistance: 'Home assistance',
      minorRepairs: 'Minor Repairs',
      petServices: 'Pet Services',
      companionService: 'Companion Service',
      marketingPromotion: 'Marketing & Promotion',
      lockSmith: 'Lock Smith',
      gardenCleaning: 'Garden cleaning',
      allOrder: 'All order',
      confirm: 'Confirm',
      completed: 'Completed',
      viewOrder: 'View order',
      progress: 'Progress',
      created: 'Created',
      request: 'Offer Help',
      requestTitle: 'Offer Help',
      accept: 'Accept',
      decline: 'Decline',
      chooseServiceCategory: 'Choose Your Service Category',
      review: 'Review',
      cantUndo: "You can't undo this later",
      taskCompleted: 'task completed',
      tasks: 'tasks',
      reviews: 'reviews',
      skills: 'Skills',
      seeMore: 'See more',
      noOrders: 'No orders',
      giveFeedback: 'Give feedback',
      giveAFeedback: 'Give a feedback',
      deleted: 'Deleted',
      orderDeleted: 'Order deleted successfully',
      rateExperience: 'How was your experience?',
      feedbackDesc: 'Your feedback helps improve service quality.',
      rateMark: 'Rate your experience',
      shareExperienceHint: 'Share your experience...',
      submitReview: 'Submit Review',
      reviewSubmitted: 'Review submitted!',
      pleaseSelectRating: 'Please select a star rating.',
      rateExpTitle: 'Rate Experience',
      postedBy: 'Posted by',
      distance: 'Distance',
      offerHelp: 'Offer Help',
      orderOtp: 'Order OTP',
      nicolas: 'Nicolas',
      alexSmith: 'Alex Smith',
      thankYouFeedback: 'Thank you for your feedback!',
      reviewSubmittedSuccess: 'Your review has been submitted successfully.',
      backToHome: 'Back to home',
      messages: 'Messages',
      typeMessage: 'Type a message',
      billingAndPayments: 'Billing & payments',
      manageBillingMethod: 'Manage billing method',
      manageBillingDesc: 'Add, update or remove methods.',
      addBillingMethod: 'Add a billing method',
      cardNumber: 'Card number',
      cardHolderName: 'Card holder name',
      mm: 'MM',
      yy: 'YY',
      cvc: 'CVC',
      address: 'Address',
      postalCode: 'Postal code',
      paymentSuccessful: 'Payment Successful',
      amount: 'Amount',
      paymentMethod: 'Payment method',
      enterAmount: 'Enter Amount',
      paymentIsReleased: 'Payment is realeased only after completion.',
      pay: 'Pay',
      account: 'Account',
      changePassword: 'Change password',
      payment: 'Payment',
      about: 'About',
      signOut: 'Sign out',
      supportTicket: 'Support Ticket',
      currentPassword: 'Current password',
      newPassword: 'New password',
      confirmPassword: 'Confirm password',
      forgotPassword: 'Forgot password?',
      subject: 'Subject',
      orderLabel: 'Order',
      attachment: 'Attachment',
      yourMessage: 'Your message',
      nameExample: 'name@example.com',
      selectYourOrder: 'select your order',
      addAttachment: 'add attachment',
      termsConfirmText1: 'By submitting this form, you confirm that you have read and agree to Worker\'s ',
      termsConfirmText2: ' and ',
      privacyStatement: 'Privacy Statement',
      photo: 'Photo',
      name: 'Name',
      changeName: 'Change your name',
      changeEmail: 'Change email address',
      changePhoneNumber: 'Change phone number',
      changeCity: 'Change City',
      changePhoto: 'Change your photo',
      language: 'Language',
      english: 'English',
      chinese: 'Chinese',
      sanFranciscoCA: 'San Francisco CA',
      taskCompletedCount: 'task completed',
      notificationRequest: '@user accepted your @task request.',
      notificationMessage: 'New message from @user regarding your task.',
      notificationSystem: 'System notification: @text',
      reposts: 'Reposts',
      overview: 'Overview',
      transactionHistory: 'Transaction history',
      refId: 'Ref ID: @id',
      serviceFee: 'Service fee',
      deposit: 'Deposit',
      takePhoto: 'Take a Photo',
      chooseFromLibrary: 'Choose from library',
      report: 'Earnings and Transactions',
      workInProgress: 'Work in progress',
      inReview: 'In review',
      available: 'Available',
      notificationCompleted: '@task task has been completed.',
      notificationRate: 'Rate your experience with @name',
      timeHoursAgo: 'h',
      timeMinutesAgo: 'm',
      strikeLateCancellation: 'You received a strike due to late cancellation.',
      visibilityAffected: 'Your visibility may be affected.',
      justNow: 'now',
      phoneHint: '+1 887 394 0392',
      shortBio: 'Short bio',
      tellYourWorkExp: 'Tell your work experience',
      proposedBudget: 'Proposed budget',
      submitRequest: 'Submit request',
      reset: 'Reset',
      apply: 'Apply',
      myJob: 'My Job',
      allJob: 'All Job',
      accepted: 'Accepted',
      pending: 'Pending',
      viewTask: 'View task',
      confirmed: 'Confirmed',
      startWork: 'Start work',
      finishWork: 'Finish work',
      completeTheTask: 'Complete the task',
      otpInstruction:
          'Ask the buyer for the 6-digit OTP to confirm job completion.',
      completeWork: 'Complete work',
      accountVerification: 'Account verification',
      documentVerification: 'Document verification',
      documentType: 'Document type',
      idCard: 'ID Card',
      passport: 'Passport',
      fullName: 'Full name',
      dateOfBirth: 'Date of birth',
      idNumber: 'ID number',
      takePicturesOfId: 'Take pictures of your goverment issued ID card',
      provideIdInfo: 'Please provide your ID Card information',
      verified: 'Verified',
      notVerified: 'Not Verified',
      placeIdInFrame: 'Place the ID Card in the frame',
      verificationSuccessful: 'Verification successful',
      verificationFailed: 'Verification Failed',
      close: 'Close',
      tryAgain: 'Try Again',
      confirmLocation: 'Confirm Location',
      myLocation: 'My Location',
      camera: 'Camera',
      photoGallery: 'Photo Gallery',
      document: 'Document',
      submitTicket: 'Submit Ticket',
      attention: 'Attention',
      acceptTermsWarning: 'Please accept the Terms and Privacy Statement',
      success: 'Success',
      ticketSubmitted: 'Your ticket has been submitted successfully',
      ticketHistory: 'Ticket History',
      resolved: 'Resolved',
      paymentBanner: 'Payment is released only after completion.',
      chatBanner:
          'For your security, please do not communicate or share payment details outside the app.',
      orderBanner:
          "Don't share the completion OTP with your worker if the work is not yet done.",
      successBanner:
          'Please wait a moment while we find requests from nearby workers.',
      privacyBanner:
          'Your privacy is our priority. We never share your personal documents with third parties.',
      beFirstToHelp: 'Be the first to help someone today!',
      noRequestsRightNow:
          'There are no requests here right now.\nCheck back soon!',
      securePayment: '100% Secure Payment',
      paymentReleasedCompletion:
          '• Payment is released ONLY after you confirm the completion.',
      beSpecificDetails:
          "• Be specific in your details (e.g., 'Need someone with a power drill').",
      tenKVerified: '10k+',
      oneHundredPercent: '100%',
      ninetyNinePercent: '99%',
      helpers: 'Helpers',
      securePayBadge: 'Secure Pay',
      successRate: 'Success Rate',
      communitySafetyOtp:
          'To keep our community safe, we use OTP verification for logging in, signing up, and confirming completed jobs.',
      signOutConfirm: 'Are you sure you want to sign out?',
      viewRequest: 'View Request',
    },
    'zh_CN': {
      viewRequest: '查看请求',
      appName: '帮',
      getStarted: '立即开始',
      selectLanguage: '选择语言',
      cancel: '取消',
      done: '完成',
      skip: '跳过',
      next: '下一步',
      edit: '编辑',
      remove: '移除',
      delete: '删除',
      change: '更改',
      save: '保存',
      continueText: '继续',
      or: '或者',
      update: '更新',
      search: '搜索',
      cad: '加元',
      letsGo: '出发吧',
      findTrustedHelp: '在附近寻找值得信赖的帮手',
      chatTrackGet: '聊天、追踪并完成任务',
      postTasks: '几分钟内发布任务',
      onBoardingSubTitle1: '发布任务并与社区中可靠的人联系。',
      onBoardingSubTitle2: '轻松管理您的任务并追踪进度。',
      onBoardingSubTitle3: '保证安全的通讯和付款。',
      createAccount: '创建账户',
      signIn: '登录',
      tellUsAboutYourself: '介绍一下你自己',
      iNeedHelp: '我需要帮助',
      iNeedHelpDesc: '从附近的专业人士那里获得帮助以完成事务',
      iWantToWork: '我想工作',
      iWantToWorkDesc: '在安全赚钱的同时帮助社区',
      firstName: '名',
      lastName: '姓',
      email: '电子邮件',
      password: '密码',
      phoneNumber: '电话号码',
      city: '城市',
      alreadyHaveAccount: '已经有账户了？',
      orCreateAccount: '或者创建账户',
      signUp: '注册',
      continueWithGoogle: '使用 Google 继续',
      continueWithApple: '使用 Apple 继续',
      termsOfService: '服务条款',
      privacyPolicy: '隐私政策',
      bySigningUp: '注册即表示您同意我们的',
      and: '和',
      enterVerificationCode: '输入验证码',
      codeSentTo: '验证码将发送至',
      resendCode: '重新发送',
      haventGotCode: "还没有收到验证码？",
      home: '首页',
      order: '订单',
      message: '消息',
      profile: '个人资料',
      letLocal: '让当地',
      expertsHelp: '专家帮助',
      you: '你',
      letLocalExperts: '让当地专家为您提供帮助',
      create: '发布任务',
      serviceCategory: '服务类别',
      locationName: '旧金山',
      addressDetail: '惠灵顿街75号，安大略省 K1A 0A2',
      notification: '通知',
      createTask: '发布任务',
      category: '类别',
      chooseCategory: '选择类别',
      taskTitle: '任务标题',
      taskTitleHint: '例如：组装宜家桌子',
      addressArea: '地址/区域',
      addressHint: '例如：旧金山 CA',
      selectDate: '选择日期',
      selectTime: '选择时间',
      details: '详情',
      detailsHint: '描述任务',
      budget: '预算',
      budgetHint: '80-100美元',
      postTask: '发布任务',
      goOrder: '转到我的订单',
      taskPosted: '您的任务已发布。接下来该怎么做？',
      taskerRequestOffer: '帮手请求报价',
      chatAndGetItDone: '沟通并完成任务！',
      goToMyTask: '转到我的任务',
      furnitureAssembly: '家具组装',
      homeAssistance: '家庭协助',
      minorRepairs: '微修',
      petServices: '宠物服务',
      companionService: '陪护服务',
      marketingPromotion: '营销与推广',
      lockSmith: '锁匠',
      gardenCleaning: '花园清洁',
      allOrder: '所有订单',
      confirm: '确认',
      completed: '已完成',
      viewOrder: '查看订单',
      progress: '进行中',
      created: '已创建',
      request: '请求',
      requestTitle: '请求',
      accept: '接受',
      decline: '拒绝',
      chooseServiceCategory: '选择您的服务类别',
      review: '评价',
      cantUndo: "此操作无法撤销",
      taskCompleted: '已完成任务',
      tasks: '任务',
      reviews: '评价',
      skills: '技能',
      seeMore: '查看更多',
      noOrders: '没有订单',
      giveFeedback: '给予反馈',
      giveAFeedback: '给予反馈',
      deleted: '已删除',
      orderDeleted: '订单删除成功',
      rateExperience: '您的体验如何？',
      feedbackDesc: '您的反馈有助于提高服务质量。',
      rateMark: '请评价您的体验',
      shareExperienceHint: '分享您与工人的经历...',
      submitReview: '提交评价',
      reviewSubmitted: '评价提交成功！',
      pleaseSelectRating: '请选择星级评分。',
      rateExpTitle: '评价体验',
      postedBy: '发布者',
      distance: '距离',
      offerHelp: '提供帮助',
      orderOtp: '订单动态密码',
      nicolas: '尼古拉斯',
      alexSmith: '亚历克斯·史密斯',
      thankYouFeedback: '感谢您的反馈！',
      reviewSubmittedSuccess: '您的评价已成功提交。',
      backToHome: '返回主页',
      messages: '消息',
      typeMessage: '输入消息',
      billingAndPayments: '账单与支付',
      manageBillingMethod: '管理账单方式',
      manageBillingDesc: '添加、更新或删除您的账单方式。',
      addBillingMethod: '添加账单方式',
      cardNumber: '卡号',
      cardHolderName: '持卡人姓名',
      mm: '月',
      yy: '年',
      cvc: '验证码',
      address: '地址',
      postalCode: '邮政编码',
      paymentSuccessful: '支付成功',
      amount: '金额',
      paymentMethod: '付款方式',
      enterAmount: '输入金额',
      paymentIsReleased: '付款仅在完成后发放。',
      pay: '支付',
      account: '账户',
      changePassword: '修改密码',
      payment: '支付',
      about: '关于我们',
      signOut: '退出登录',
      supportTicket: '支持工单',
      currentPassword: '当前密码',
      newPassword: '新密码',
      confirmPassword: '确认密码',
      forgotPassword: '忘记密码？',
      subject: '主题',
      orderLabel: '订单',
      attachment: '附件',
      yourMessage: '您的留言',
      nameExample: 'name@example.com',
      selectYourOrder: '选择您的订单',
      addAttachment: '添加附件',
      termsConfirmText1: '提交此表单即表示您确认已阅读并同意Worker的',
      termsConfirmText2: ' 以及 ',
      privacyStatement: '隐私声明',
      photo: '照片',
      name: '名字',
      changeName: '更改名字',
      changeEmail: '更改邮箱',
      changePhoneNumber: '更改电话',
      changeCity: '更改城市',
      changePhoto: '更改照片',
      language: '语言',
      english: '英语',
      chinese: '中文',
      sanFranciscoCA: '加利福尼亚州旧金山',
      taskCompletedCount: '个任务已完成',
      notificationRequest: '@user 接受了您的 @task 请求。',
      notificationMessage: '收到来自 @user 的关于您任务的新消息。',
      notificationSystem: '系统通知: @text',
      reposts: '转发记录',
      overview: '概览',
      transactionHistory: '交易记录',
      refId: '参考ID: @id',
      serviceFee: '服务费',
      deposit: '存款',
      takePhoto: '拍照',
      chooseFromLibrary: '从图库选择',
      report: '收益与交易',
      workInProgress: '进行中的工作',
      inReview: '审核中',
      available: '可用',
      notificationCompleted: '@task 任务已完成。',
      notificationRate: '评价您与 @name 的体验',
      timeHoursAgo: '小时',
      timeMinutesAgo: '分钟',
      justNow: '刚刚',
      phoneHint: '+86 138 0013 8000',
      shortBio: '个人简介',
      tellYourWorkExp: '描述您的工作经验',
      proposedBudget: '建议预算',
      submitRequest: '提交请求',
      reset: '重置',
      apply: '应用',
      myJob: '我的工作',
      allJob: '所有工作',
      accepted: '已接受',
      pending: '待定',
      viewTask: '查看任务',
      confirmed: '已确认',
      startWork: '开始工作',
      finishWork: '完成工作',
      completeTheTask: '完成任务',
      otpInstruction: '向买家询问6位OTP以确认工作完成。',
      completeWork: '完成工作',
      accountVerification: '账户验证',
      documentVerification: '证件验证',
      documentType: '证件类型',
      idCard: '身份证',
      passport: '护照',
      fullName: '全名',
      dateOfBirth: '出生日期',
      idNumber: '证件号码',
      takePicturesOfId: '拍摄您的政府颁发的身份证件',
      provideIdInfo: '请提供您的身份证信息',
      verified: '已验证',
      notVerified: '未验证',
      placeIdInFrame: '请将身份证放入框内',
      verificationSuccessful: '验证成功',
      verificationFailed: '验证失败',
      close: '关闭',
      tryAgain: '重试',
      confirmLocation: '确认位置',
      myLocation: '我的位置',
      camera: '摄像头',
      photoGallery: '照片库',
      document: '文档',
      submitTicket: '提交服务单',
      attention: '注意',
      acceptTermsWarning: '请接受条款和隐私声明',
      success: '成功',
      ticketSubmitted: '您的服务单已成功提交',
      ticketHistory: '服务单历史',
      resolved: '已解决',
      paymentBanner: '付款仅在完成后发放。',
      chatBanner: '为了您的安全，请不要在应用程序之外沟通或共享付款细节。',
      orderBanner: '如果工作尚未完成，请不要与您的工人共享完成 OTP。',
      successBanner: '请稍等片刻，我们正在寻找附近工人的请求。',
      privacyBanner: '您的隐私是我们的首要任务。我们绝不会与第三方共享您的个人文件。',
      beFirstToHelp: '今天成为第一个帮助别人的人！',
      noRequestsRightNow: '现在这里没有请求。\n请稍后再来！',
      securePayment: '100% 安全支付',
      paymentReleasedCompletion: '• 付款仅在您确认完成后发放。',
      beSpecificDetails: '• 详述细节（例如：“需要带电钻的人”）。',
      tenKVerified: '10k+',
      oneHundredPercent: '100%',
      ninetyNinePercent: '99%',
      helpers: '帮手',
      securePayBadge: '安全支付',
      successRate: '成功率',
      communitySafetyOtp: '为了维护社区安全，我们使用动态验证码（OTP）进行登录、注册及确认工作完成。',
      signOutConfirm: '您确定要退出吗？',
    },
  };
}
